language: node_js
node_js:
  - "8"
services:
  - postgresql
before_script:
  - cp src/config/config.js.travis src/config/config.js
  - psql -c 'create database api_test;' -U postgres
script:
  - npm run coverage-rep
  - codecov
env:
  global:
    - JWT_SECRET=thisisanawesomesecretpleasedonttellanyone
    - JWT_TTL=12
#after_success: 'npm run coveralls'