language: node_js
node_js:
  - "8"
services:
  - postgresql
before_script:
  - cp src/config/config.json.travis src/config/connection.json
  - psql -c 'create database api_test;' -U postgres
script:
  - npm run coverage-rep
  - codecov
#after_success: 'npm run coveralls'