language: node_js
node_js:
  - "8"
services:
  - postgresql
before_script:
  - cp config/connection.json.travis config/connection.json
  - psql -c 'create database api_test;' -U postgres
script: npm run coverage
after_success: 'npm run coveralls'